name: {{ project_name }} CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
    - uses: actions/checkout@v3
    - uses: abatilo/actions-poetry@v2.1.4
      with:
        poetry-version: 1.1.13
    - name: Test with Django
      run: |
        poetry install
        poetry run pytest --migrations
